### ISSUE TITLE
Returning indexes 

### ISSUE THREAD

**Issue by buyalsky** [buyalsky/ordered-hash-set#2]
OrderedSet's `add` method should return index of the added item. If the item is already in the OrderedSet instance, the method should return the index it already had.
Similarly, `remove` method should return index of the removed item.

Example:
```python3
s = OrderedSet()
s.add('Foo') # Should return 0
s.add('Bar') # Should return 1
s.add('Foo') # Should return 0 since 'Foo' is already in OrderedSet and its index is 0
s.remove('Bar') # Should return 1
```

**Comment by glyve99** [comment]
Hey, I think I can handle it...

**Comment by buyalsky** [comment]
Hi @glyve99, thank you for interesting the project. If you have any questions, please let me know.

**Comment by neodark** [comment]
I was going to submit a PR...

**Comment by buyalsky** [comment]
Sorry to hear that @neodark. I have already assigned it to @glyve99. I cannot review your PR unless @glyve99 unassign themself. I can prepare another beginner-friendly issue if you want to.

**Comment by neodark** [comment]
Oh that's unfortunate. Based on fairness could you please unassign yourself @glyve99 ?

Sure depending on the new issue, I can have a look at it too @buyalsky or it can be assigned to the other contributor .

**Comment by buyalsky** [comment]
Hi @neodark and @glyve99, I have created a new issue. You can check this out: #4.

**Comment by glyve99** [comment]
Hey @neodark, sorry I wasnt seeing the comment section, I just sent the PR

**Comment by neodark** [comment]
@glyve99 : Your implementation seems a bit unoptimized indeed and some issues are present. Example in your remove function implementation that has a zero-index defined as default, which could cause issues.

**Comment by VaibhavDS19** [comment]
Can I try this?

**Comment by buyalsky** [comment]
Hi @VaibhavDS19. 
Unfortunately, this issue is already assigned to @glyve99. 
But feel free to check out any other issues.
