### ISSUE TITLE
Missing methods

### ISSUE THREAD

**Issue by buyalsky** [buyalsky/ordered-hash-set#4]
Currently, some useful [Built-in Set](https://docs.python.org/3.7/library/stdtypes.html#set) methods do not exist in OrderedSet, such as:

- [x] is_disjoint
- [x] is_subset
- [x] is_superset
- [x] intersection
- [x] difference
- [x] union

We need to add these functionalities as an enhancement. Please see [this page](https://www.programiz.com/python-programming/methods/set) for some examples.

**Comment by gremlin97** [comment]
Hi, I would like to work on this issue!

**Comment by thelilnix** [comment]
Hey @buyalsky, can I work on it?

**Comment by buyalsky** [comment]
Sure @ebsa491, it's yours. You can implement any of the methods as you wish. But, please do not forget to add tests.
